# Generated by Django 5.0.4 on 2024-06-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userjobinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobinformation',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Is Valid'),
        ),
    ]
