# Generated by Django 5.0.4 on 2024-06-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userjobinformation_is_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjobinformation',
            old_name='is_valid',
            new_name='is_submitted',
        ),
    ]
