# Generated by Django 5.0.4 on 2024-06-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_is_valid_userjobinformation_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobinformation',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='is_submitted'),
        ),
    ]
