# Generated by Django 5.0.4 on 2024-06-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_userjobinformation_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
