# Generated by Django 5.0.4 on 2024-06-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='answered',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Answered'),
        ),
    ]
