# Generated by Django 5.0.4 on 2024-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='dweet_file',
            field=models.FileField(blank=True, null=True, upload_to='dweet_file/', verbose_name='Dweet File'),
        ),
    ]
