# Generated by Django 5.0.4 on 2024-05-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dweet_dweet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='content',
            field=models.CharField(max_length=300, verbose_name='Content'),
        ),
    ]
